# Docker
# Build and push an image to Docker Hub every time there is a new commit on the dev branch

trigger:
- dev

resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Jacob''s Docker Hub'
    repository: 'jpbulloch5/revature_p1_orm'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      $(Build.BuildId)
      latest_dev
  displayName: Build ORM in container and push image to DockerHub
