# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Jacob''s Docker Hub'
    repository: 'jpbulloch5/revature_p1_orm'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
  displayName: Build ORM in container and push image to DockerHub
