# Docker
# Build and push an image to Docker Hub every time there is a new commit on the dev branch

trigger:
 - dev 

steps:
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: '20.150.209.143 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGbr1M7nadLbuGXmJqEagWz0B5mDQvKuZDzM9ODE0b3M'
    sshKeySecureFile: 'Flock-of-Hawks-2_key'

- task: Ansible@0
  inputs:
    ansibleInterface: 'agentMachine'
    playbookPathOnAgentMachine: './setup.yml'
    inventoriesAgentMachine: 'file'
    inventoryFileOnAgentMachine: './inventory'
    sudoEnabled: true
