# Docker
# Build and push an image to Docker Hub every time there is a new commit on the main branch
# This pipeline pushes the 'latest' image to Docker Hub instead of 'latest_dev', which is 
# triggered by updates to the dev branch

trigger:
- main

resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Jacob''s Docker Hub'
    repository: 'jpbulloch5/revature_p1_orm'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
  displayName: Build ORM in container and push image to DockerHub
