# Docker
# Build and push an image to Docker Hub every time there is a new commit on the main branch
# This pipeline pushes the 'latest' image to Docker Hub instead of 'latest_dev', which is 
# triggered by updates to the dev branch

# switching off the trigger for now so that it doesn't take up resources
trigger:
- main

resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Jacob''s Docker Hub'
    repository: 'jpbulloch5/revature_p1_orm'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
  displayName: Build ORM in container and push image to DockerHub

- task: ado-discord-webhook@1
  inputs:
    channelId: '$(discord_id)'
    webhookKey: '$(discord_webhook)'
    name: '$(System.TeamProject) --> '
    avatar: 'https://avatarfiles.alphacoders.com/565/thumb-1920-56514.jpg'
    messageType: 'content'
    content: |
      __**$(Build.DefinitionName)**__
      **Build:** $(Build.BuildNumber)
      **Reason:** $(Build.Reason)
      **Status:** $(Agent.JobStatus)
      **Repo:** $(Build.Repository.Uri)
      **Message:** $(Build.SourceVersionMessage)
  condition: always()
  displayName: send message to Discord 