---
- name:
  hosts: all
  tasks:

  - name: Ensure PostgreSQL is present
    become: yes
    apt:
        name: [ 'postgresql', 'postgresql-contrib' ]
        state: latest
    
  - name: Create and initialize airline_db
    become: yes
    become_user: postgres
    command:
      chdir: /home
      cmd: psql -U postgres -d postgres -a -f airline_db.sql

  

