---
- name:
  hosts: all
  tasks:

  - name: Ensure PostgreSQL is present
    become: yes
    apt:
        name: [ 'postgresql', 'postgresql-contrib' ]
        state: latest

  - name: Set postgres password
    become: yes
    become_user: postgres
    command:
      chdir: /home
      cmd: psql -U postgres -d postgres -a -f password.sql

  - name: Create airline_db database 
    become: yes
    become_user: postgres
    command:
      cmd: createdb -e -h localhost -p 5432 -U postgres airline_db
      stdin: 
      - password123
      - exit
    
  - name: Create and initialize airline_db
    become: yes
    become_user: postgres
    command:
      chdir: /home
      cmd: psql -U postgres -d postgres -a -f airline_db.sql

  

