---
- hosts: all
  tasks:
    - name: install apt repository
      become: yes
      apt:
        name: software-properties-common
        state: latest
    - name: Add Oracle Java Repository
      become: yes
      apt_repository:
        repo: 'ppa:webupd8team/java'
    - name: Accept Java 8 Liscense
      become: yes
      debconf:
        name: 'oracle-java8-installer'
        question: 'shared/accepted-oracle-liscense-v1-1'
        value: 'true'
        vtype: 'select'
    - name: oracle-java8-installer
      become: yes
      apt:
        name: oracle-java8-installer
        update_cache: yes
        state: latest
    - name: ca-certificates
      become: yes
      apt:
        name: ca-certificates
        state: latest
    - name: oracle-java8-set-default
      become: yes
      apt:
        name: oracle-java8-set-default
        state: latest
    - name: create folder
      file: 
        path: /home/azureuser/tomcat
        state: directory
        mode: 0755
    - name: Download Tomcat
      get_url: 
        url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.27/bin/apache-tomcat-8.0.27.tar.gz
        dest: /home/azureuser/tomcat
    - name: Extract Archive
      unarchive: 
        src: /home/azureuser/tomcat/apache-tomcat-8.0.27.tar.gz
        dest: /home/azureuser/tomcat
 