
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# - task: MavenAuthenticate@0
#   inputs:
#     artifactsFeeds: 'Flock-of-Hawks-Artifacts'
#   displayName: Authenticate Flock-of-Hawks-Artifacts with Maven

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'VM3 SonarQube'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner,
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=Flock_of_Hawks_team_e_p1_orm
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    isJacocoCoverageReportXML: true
    sqMavenPluginVersionChoice: 'latest'

- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'


- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.SourcesDirectory)/target/eorm-1.0.jar'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '24909f86-8d03-4826-8947-55d471b47b72/57273a34-95c4-4b34-8b08-4600b3975070'
    vstsFeedPackagePublish: 'orm-jar-package'
    versionOption: 'patch'
    packagePublishDescription: 'orm jar file'
    verbosity: 'Debug'

- task: ado-discord-webhook@1
  inputs:
    channelId: '856747431500447755'
    webhookKey: 'pnX9mrDlsv86zWC7VMmGQfR9vhvwEGqxWGJjDKyEXltzpPmzwTnC-zz85drbHeZaxw3C'
    name: 'Flock of Hawks --> test_ORM'
    avatar: 'https://avatarfiles.alphacoders.com/565/thumb-1920-56514.jpg'
    messageType: 'content'
    content: '**Build Number:**```$(Build.BuildNumber)```**Build Reason:**```$(Build.Reason)```**Build Status**```$(Agent.JobStatus)```'
  condition: always()
  displayName: send message to Discord 