
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'p1'
# - task: SonarQubePrepare@4
#   inputs:
#     SonarQube: 'VM3 SonarQube'
#     scannerMode: 'Other'
#     extraProperties: |
#       # Additional properties that will be passed to the scanner,
#       # Put one key=value per line, example:
#       # sonar.exclusions=**/*.bin
#       sonar.projectKey=Flock_of_Hawks_team_e_p1_orm
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

# - task: SonarQubePublish@4
#   inputs:
#     pollingTimeoutSec: '300'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/s/target/eorm-1.0.jar'
    artifact: 'ORM_JAR'
    publishLocation: 'pipeline'