
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'Flock-of-Hawks-Artifacts'

# - task: SonarQubePrepare@4
#   inputs:
#     SonarQube: 'VM3 SonarQube'
#     scannerMode: 'Other'
#     extraProperties: |
#       # Additional properties that will be passed to the scanner,
#       # Put one key=value per line, example:
#       # sonar.exclusions=**/*.bin
#       sonar.projectKey=Flock_of_Hawks_team_e_p1_orm
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

# - task: SonarQubePublish@4
#   inputs:
#     pollingTimeoutSec: '300'


- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '**/*.jar'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '24909f86-8d03-4826-8947-55d471b47b72/57273a34-95c4-4b34-8b08-4600b3975070'
    vstsFeedPackagePublish: 'orm-jar-package'
    versionOption: 'patch'
    packagePublishDescription: 'orm jar file'
    verbosity: 'Debug'